---
- name: Change Cisco hostname
  hosts: R1
  gather_facts: no
  tasks:
    - name: Change hostname to testing
      cisco.ios.ios_config:
        lines:
          - hostname testing
        after:
          - show running-config | include hostname
        
      register: result
      become: yes
      become_method: enable

    - name: Show output of the configuration
      debug:
        var: result
