---
- name: Change Cisco hostname
  hosts: R1
  gather_facts: no
  tasks:
    - name: Change hostname to testing
      cisco.ios.ios_config:
        authorize: yes
        config:
          - hostname testing
      register: result

    - name: Show output of the configuration
      debug:
        var: result
