---
- name: Change Cisco hostname
  hosts: R1
  gather_facts: no
  tasks:
  
    - name: Change hostname to testing
      ios_config:
        lines:
          - "hostname testing"
        save_when: modified
      register: result
      become: yes
      become_method: enable

    - name: Show output of the configuration
      debug:
        var: result
