---
- name: Change Cisco hostname
  hosts: cisco_routers
  gather_facts: no
  tasks:
    - name: Change hostname to testing
      cisco.ios.ios_config:
        authorize: yes
        config:
          - conf t
          - hostname testing
          - exit
      register: result

    - name: Show output of the configuration
      debug:
        var: result
