---
- name: Configure interfaces on Cisco Routers
  hosts: all
  gather_facts: no
  tasks: 
    - name: Set interface IP address
      ios_config:
        line:
          - interface g0/1
          - ip address 192.168.0.1 255.255.255.0
          - no shutdown
        save_when: modified
