---
- name: Configure Cisco Router
  hosts: routers
  gather_facts: no
  tasks:
    - name: Set hostname
      cisco.ios.ios_config:
        authorize: yes
        config:
          - hostname Router1
    - name: Configure interface
      cisco.ios.ios_config:
        authorize: yes
        config:
          - interface g0/1
          - ip address 10.0.0.1 255.255.255.252
          - no shut
