---
- name: Verify Interface Status CISCO
  hosts: R1
  gather_facts: no
  tasks:
  
    - name: Show interfaces
      ios_config:
        lines:
          - show ip interface brief
        register: result 

    - name: Print Contents
      debug:
        var: result 
