---
- name: Verify Interface Status CISCO
  hosts: R1
  gather_facts: no
  tasks:
  
    - name: Show interfaces
      ios_config:
        lines:
          - show ip interface brief
        register: interface_output

    - name: Print Contents
      debug:
        msg: "{{ interface_output.stdout_lines }}"
        var: interface_output
